# Site settings
title: ProjectEuler Türkçe
email: muratcorlu@gmail.com
description: "Bu site ProjectEuler projesinin sorularının Türkçe çevirilerini teşkil eder."
baseurl: "/euler"
url: "http://muratcorlu.com"
twitter_username: muratcorlu
github_username:  muratcorlu

# Build settings
markdown: redcarpet
permalink: ":title.html"

redcarpet:
  extensions: ['superscript']