# Site settings
title: ProjectEuler Türkçe
email: muratcorlu@gmail.com
description: "Bu site ProjectEuler projesinin sorularının Türkçe çevirilerini teşkil eder."
baseurl: ""
url: "http://muratcorlu.com/euler/"
twitter_username: muratcorlu
github_username:  muratcorlu

# Build settings
markdown: kramdown
permalink: ":title.html"
